# Generated by Django 4.0.2 on 2022-03-12 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelQuoteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default='', max_length=100)),
                ('gallonsRequested', models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('deliveryAddressOne', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('deliveryAddressTwo', models.CharField(max_length=100)),
                ('deliveryDate', models.DateField()),
                ('pricePerGallon', models.BigIntegerField()),
                ('totalDue', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default='', max_length=100, unique=True)),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default='', max_length=100, unique=True)),
                ('fullName', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('addressOne', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('addressTwo', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('inState', models.BinaryField(default=True)),
                ('zipCope', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
    ]
