# Generated by Django 4.0.2 on 2022-03-13 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='zipCope',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipCode',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='fuelquoteform',
            name='deliveryAddressOne',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fuelquoteform',
            name='deliveryAddressTwo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelquoteform',
            name='deliveryDate',
            field=models.DateField(default='01/01/2020'),
        ),
        migrations.AlterField(
            model_name='fuelquoteform',
            name='gallonsRequested',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fuelquoteform',
            name='pricePerGallon',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fuelquoteform',
            name='totalDue',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='addressOne',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='addressTwo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inState',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
