# Generated by Django 4.0.2 on 2022-05-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userID',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
