# Generated by Django 4.0.2 on 2022-03-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_login_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
