# Generated by Django 4.0.2 on 2022-05-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_username_userprofile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='userID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
