# Generated by Django 4.0.2 on 2022-03-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelquoteform',
            name='gallonsRequested',
            field=models.BigIntegerField(default=0),
        ),
    ]
